server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://user:password@cluster0.zdl9n.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
